Add(Product): Inc/Dec input text
mgdeveloper45/Heidi-Skin16 pull request #25
Opened 2022-05-04 23:00 UTC by AriAgress

2022-05-04 23:04 UTC, seenanadimi requested changes
add quantity state to dispatch(addToCart({ ...products[index], quantity: quantity}))

2022-05-04 23:05 UTC, aleon510 approved these changes
WIP, LGTM

2022-05-05 00:05 UTC, seenanadimi approved these changes
LGTM!

2022-05-05 00:05 UTC, mgdeveloper45 approved these changes

2022-05-05 00:06 UTC, merged